development:
  adapter: postgresql
  database: bolao_dev
  username: postgres
  password: postgres
  host: 127.0.0.1
  encoding: utf8

test:
  adapter: postgresql
  database: bolao_test
  username: postgres
  password: postgres
  host: 127.0.0.1
  encoding: utf8

production:
  adapter: postgresql
  database: bolaomegasena
  username: postgres
  password: postgres
  host: 127.0.0.1
  encoding: utf8
